export const seedWarnings = [
  {
    title: 'Beaches',
    type: 'Movie',
    year: '1988',
    intensity: 'Very High',
    tags: ['Cancer death', 'Friendship grief', 'Hospital scenes', 'End-of-life'],
    spoilerFree: 'Major cancer storyline involving decline, caregiving, friendship, grief, and death.',
    spoilerDetails: 'A main character becomes seriously ill and dies from cancer. End-of-life and grief themes are central to the story.',
    status: 'approved',
    createdAtText: 'Seed entry'
  },
  {
    title: 'A Walk to Remember',
    type: 'Movie',
    year: '2002',
    intensity: 'High',
    tags: ['Leukemia', 'Teen illness', 'Death implied', 'Faith themes'],
    spoilerFree: 'A central romance includes a serious cancer diagnosis and anticipatory grief.',
    spoilerDetails: 'The main female character has leukemia. The story strongly implies she dies after marrying the male lead.',
    status: 'approved',
    createdAtText: 'Seed entry'
  },
  {
    title: 'Stepmom',
    type: 'Movie',
    year: '1998',
    intensity: 'Very High',
    tags: ['Parent with cancer', 'Terminal cancer', 'Children grieving', 'Family preparation'],
    spoilerFree: 'A mother experiences a terminal cancer storyline with family grief and preparation for loss.',
    spoilerDetails: 'The mother has terminal cancer and prepares her children and family for life after her death.',
    status: 'approved',
    createdAtText: 'Seed entry'
  },
  {
    title: 'The Fault in Our Stars',
    type: 'Book/Movie',
    year: '2012 / 2014',
    intensity: 'Very High',
    tags: ['Young adults with cancer', 'Recurrence', 'Death', 'Support group'],
    spoilerFree: 'Cancer is central to the plot, including recurrence, serious decline, and grief.',
    spoilerDetails: 'Two young people with cancer fall in love. One experiences recurrence and dies.',
    status: 'approved',
    createdAtText: 'Seed entry'
  },{
  id: 'terms-of-endearment',
  title: 'Terms of Endearment',
  type: 'Movie',
  year: '1983',
  intensity: 'Very High',
  status: 'approved',
  tags: ['Parent with Cancer', 'Children grieving', 'Hospital Scenes', 'Cancer Death', 'Grief'],
  spoilerFree: 'Includes a parent cancer storyline, hospital scenes, family distress, and death.',
  spoilerDetails: 'A mother dies of cancer. There are intense hospital and goodbye scenes involving her children.',
  notes: 'Use care if you are parenting through cancer, grieving a mother, or sensitive to hospital goodbye scenes.'
},
{
  id: 'my-sisters-keeper',
  title: "My Sister's Keeper",
  type: 'Book',
  year: '2004',
  intensity: 'Very High',
  status: 'approved',
  tags: ['Child with Cancer', 'Medical Trauma', 'Family illness', 'Cancer Death', 'Caregiver grief'],
  spoilerFree: 'Centers on childhood cancer, family medical decisions, hospital life, and grief.',
  spoilerDetails: 'A child’s leukemia and family medical/legal conflict drive the plot. Death and medical trauma themes are prominent.',
  notes: 'May be especially tender for parents, siblings, caregivers, and anyone affected by childhood cancer or medical decision-making trauma.'
},
{
  id: 'dead-to-me',
  title: 'Dead to Me',
  type: 'TV Show',
  year: '2019–2022',
  intensity: 'High',
  status: 'approved',
  tags: ['Breast Cancer', 'Cancer Recurrence', 'Medical anxiety', 'Friendship', 'Grief'],
  spoilerFree: 'Later episodes include cancer-related medical uncertainty and emotionally heavy friendship themes.',
  spoilerDetails: 'Cancer becomes part of a major character’s storyline in the later seasons, including testing, treatment decisions, and mortality fears.',
  notes: 'Use care if recurrence fear, medical testing, or breast cancer-related uncertainty feels activating.'
},
{
  id: 'breaking-bad',
  title: 'Breaking Bad',
  type: 'TV Show',
  year: '2008–2013',
  intensity: 'High',
  status: 'approved',
  tags: ['Cancer Diagnosis', 'Chemo', 'Family illness', 'Medical anxiety', 'Lung cancer'],
  spoilerFree: 'The series begins with a lung cancer diagnosis and includes treatment, fear of death, and family impact.',
  spoilerDetails: 'A cancer diagnosis motivates the central storyline. Treatment and prognosis are revisited throughout the series.',
  notes: 'May feel heavy for viewers newly diagnosed, in treatment, or supporting a loved one with cancer.'
}
];

export const cancerTags = [
  'Cancer Diagnosis',
  'Recurrence',
  'Cancer Death',
  'Parent with Cancer',
  'Child with Cancer',
  'Spouse/partner with Cancer',
  'Chemo',
  'Radiation',
  'Hair loss',
  'Mastectomy',
  'Body Image',
  'Hospital Scenes',
  'Hospice',
  'End-of-life',
  'Funeral',
  'Grief',
  'Medical Trauma',
  'Infertility',
  'Survivorship',
  'Medical anxiety',
  'Family illness',
  'Caregiver grief',
  'Children grieving',
  'Anticipatory grief',
  'Metastatic cancer',
  'Surgery',
  'Faith themes',
  'Survivor guilt'
];
